script:

  flush_board1:
    alias: "Flush Board 1"
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.flush_in_progress

      # --- Board 1 Valve 1 ---
      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay1      # valve1 open
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay1

      - delay: "00:00:20"                      # 20s flush

      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay2      # valve1 close
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay2

      - delay: "00:00:20"                      # 20s between valves

      # --- Board 1 Valve 2 ---
      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay3
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay3

      - delay: "00:00:20"

      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay4
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay4

      - delay: "00:00:20"

      # --- Board 1 Valve 3 ---
      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay5
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay5

      - delay: "00:00:20"

      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay6
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay6

      - delay: "00:00:20"

      # --- Board 1 Valve 4 ---
      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay7
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay7

      - delay: "00:00:20"

      - service: switch.turn_on
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay8
      - delay: "00:00:00.500"
      - service: switch.turn_off
        target:
          entity_id: switch.athom_8ch_relay_board_b0a984_relay8

      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.flush_in_progress

      - service: notify.mobile_app_your_phone
        data:
          message: "Board 1 flush complete"

  #flush_board2 when it arrives
  #flush_board3 when it arrives